### ISSUE TITLE
Enforcing https on pages for multiple projects

### ISSUE THREAD

**Issue by harikt** [sapienphp/sapienphp.github.io#1]
Hi Paul, 

Can you enable https for all the github pages for : 

1. https://github.com/sapienphp/sapienphp.github.io/settings/pages
2. https://github.com/qiqphp/qiqphp.github.io/settings/pages
3. https://github.com/atlasphp/atlasphp.github.io/settings/pages

Documentation link : https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https

**Comment by pmjones** [comment]
Done, I think. Let me know if things look OK on your end!

**Comment by harikt** [comment]
All is well. Thank you.
